// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaiOcSqZUxYYhk2NaxSJ3C5DkQEz-HHLc',
    appId: '1:158287745689:web:dc094f92fd2e4b487ede08',
    messagingSenderId: '158287745689',
    projectId: 'evofinale',
    authDomain: 'evofinale.firebaseapp.com',
    storageBucket: 'evofinale.appspot.com',
    measurementId: 'G-7H60V38F90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0OBLFfn1AD4X_Nv02hfWo67MeTwZiUsU',
    appId: '1:158287745689:android:ebd7f882a80bb7c37ede08',
    messagingSenderId: '158287745689',
    projectId: 'evofinale',
    storageBucket: 'evofinale.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA18PJxGMLUt4-mAa1LJRNKrbN99kSgv8',
    appId: '1:158287745689:ios:3ba47c02af8688e47ede08',
    messagingSenderId: '158287745689',
    projectId: 'evofinale',
    storageBucket: 'evofinale.appspot.com',
    iosBundleId: 'com.example.evofinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA18PJxGMLUt4-mAa1LJRNKrbN99kSgv8',
    appId: '1:158287745689:ios:3ba47c02af8688e47ede08',
    messagingSenderId: '158287745689',
    projectId: 'evofinale',
    storageBucket: 'evofinale.appspot.com',
    iosBundleId: 'com.example.evofinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaiOcSqZUxYYhk2NaxSJ3C5DkQEz-HHLc',
    appId: '1:158287745689:web:b7853f1191eef2ce7ede08',
    messagingSenderId: '158287745689',
    projectId: 'evofinale',
    authDomain: 'evofinale.firebaseapp.com',
    storageBucket: 'evofinale.appspot.com',
    measurementId: 'G-CGNFTH0HQP',
  );
}
